In [1]:
from inversion import RismaData

In [3]:
risma = RismaData(workspace_dir='../assets', risma_dir='inputs/RISMA_CSV_SSM_SST_AirT_2015_2023')
risma_df = risma.load_df()

Processing file: RISMA_MB11_avg_2015_2023.csv
Processing file: RISMA_MB8_avg_2015_2023.csv
Processing file: RISMA_MB6_avg_2015_2023.csv
Processing file: RISMA_MB9_avg_2015_2023.csv
Processing file: RISMA_MB13_avg_2015_2023.csv
Processing file: RISMA_MB10_avg_2015_2023.csv
Processing file: RISMA_MB5_avg_2015_2023.csv
Processing file: RISMA_MB1_avg_2015_2023.csv
Processing file: RISMA_MB7_avg_2015_2023.csv
Processing file: RISMA_MB4_avg_2015_2023.csv
Processing file: RISMA_MB3_avg_2015_2023.csv
Processing file: RISMA_MB2_avg_2015_2023.csv
Processing file: RISMA_MB12_avg_2015_2023.csv

/home/morteza/usask/inversion/src/inversion/risma.py:80: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = df_RISMA.groupby(['date', 'station', 'depth', 'op']).apply(lambda x: x)

In [4]:
print(risma_df.shape)
risma_df.head()

(83191, 17)

,date,station,depth,op,mean_sst,mean_airt,SSM,SST,year,doy,Station,Depth (cm),bulk,Sand,Silt,Clay,Classification
0,2015-01-01,MB1,0 to 5 cm,0,-9.866667,-11.0640,0.051333,-13.488889,2015,1,MB1,5,1.28,0.7880,0.101,0.111,Sandy Loam
1,2015-01-01,MB1,0 to 5 cm,1,-9.866667,-11.0640,0.051481,-8.659259,2015,1,MB1,5,1.28,0.7880,0.101,0.111,Sandy Loam
2,2015-01-01,MB10,0 to 5 cm,0,-9.900000,-14.0045,0.242222,-11.933333,2015,1,MB10,5,1.05,0.0455,0.240,0.716,Heavy Clay
3,2015-01-01,MB10,0 to 5 cm,1,-9.900000,-14.0045,0.244037,-8.755556,2015,1,MB10,5,1.05,0.0455,0.240,0.716,Heavy Clay
4,2015-01-01,MB11,0 to 5 cm,0,-6.583333,-13.6975,0.249481,-7.140741,2015,1,MB11,5,1.30,0.2380,0.395,0.368,Clay Loam